import { FeedbackRecord } from '../types';

export const demoFeedback: FeedbackRecord[] = [
  {
    id: '1',
    date: '2026-09-10',
    feedback: 'The salesperson was extremely helpful and patient throughout the process.',
    department: 'Sales',
    sentiment: 'positive',
    category: 'Sales',
    score: 85,
  },
  {
    id: '2',
    date: '2026-09-11',
    feedback: 'I waited almost two hours past my appointment time.',
    department: 'Service',
    sentiment: 'negative',
    category: 'Wait Times',
    score: -70,
  },
  {
    id: '3',
    date: '2026-09-12',
    feedback: 'The final price had fees I was not expecting.',
    department: 'Finance',
    sentiment: 'negative',
    category: 'Pricing',
    score: -75,
  },
  {
    id: '4',
    date: '2026-09-13',
    feedback: 'Service completed the repair earlier than expected and kept me updated.',
    department: 'Service',
    sentiment: 'positive',
    category: 'Service',
    score: 80,
  },
  {
    id: '5',
    date: '2026-09-14',
    feedback: 'Nobody explained why my vehicle was still not ready.',
    department: 'Service',
    sentiment: 'negative',
    category: 'Communication',
    score: -65,
  },
  {
    id: '6',
    date: '2026-09-15',
    feedback: 'I had to call three times to get an update on my repair.',
    department: 'Service',
    sentiment: 'negative',
    category: 'Parts/Repairs',
    score: -80,
  },
  {
    id: '7',
    date: '2026-09-16',
    feedback: 'The finance manager explained everything clearly and made the process easy.',
    department: 'Finance',
    sentiment: 'positive',
    category: 'Financing',
    score: 78,
  },
  {
    id: '8',
    date: '2026-09-17',
    feedback: 'The dealership was clean and everyone was friendly.',
    department: 'Customer Experience',
    sentiment: 'positive',
    category: 'Staff',
    score: 70,
  },
  {
    id: '9',
    date: '2026-09-18',
    feedback: 'My appointment started 45 minutes late.',
    department: 'Service',
    sentiment: 'negative',
    category: 'Wait Times',
    score: -60,
  },
  {
    id: '10',
    date: '2026-09-19',
    feedback: 'The vehicle was clean and ready when I arrived for pickup.',
    department: 'Sales',
    sentiment: 'positive',
    category: 'Sales',
    score: 75,
  },
];
